(scipy)=
# Numerische Programmbibliotheken am Beispiel von NumPy/SciPy

```{admonition} Hinweis
:class: warning
Dieses Kapitel befindet sich noch in Bearbeitung.
```

In den bisherigen Kapiteln hatten wir immer wieder Gelegenheit, auf
Möglichkeiten hinzuweisen, die die Python-Standardbibliothek bietet. Wenn man
die dort zur Verfügung gestellten Module verwendet, kann man sich Einiges an
Arbeit sparen und dabei auch den Code effizienter und übersichtlicher
gestalten.  Neben der Python-Standardbibliothek gibt es aber auch noch viele
interessante Programmpakete, die häufig über den [Python Package
Index](https://pypi.org/) zur Verfügung gestellt werden.

Gerade für Problemstellungen in den Natur- und Ingenieurwissenschaften gibt es
eine oft als *scientific ecosystem of Python* oder *scientific stack*
bezeichnete Sammlung von zentralen Paketen. Hierzu gehört als Basispaket
zunächst [NumPy](http://numpy.org/), das den Datentyp `ndarray` sowie Methoden
zur Verfügung stellt, um mit `ndarray`-Objekten zu arbeiten. Damit wird das
Rechnen mit Vektoren und Matrizen ermöglicht, das wir bei der Besprechung von
Listen in {numref}`listen` vermisst hatten.

Ein weiteres wichtiges Paket ist [SciPy](https://docs.scipy.org/doc/scipy/reference/), das vielfältige numerische Werkzeuge zur Verfügung stellt, beispielsweise
zur numerischen Integration oder der Lösung von Differentialgleichungssystemen,
zur Lösung von Optimierungsproblemen oder zur Berechnung von speziellen 
Funktion sowie vielem Anderem mehr. In diesem Kapitel werden wir einen
ersten Eindruck von den Möglichkeiten geben, die NumPy und SciPy bereitstellen.

Weitere zentrale Pakete, die in diesem Zusammenhang zu nennen sind, wären
[Matplotlib](http://matplotlib.org/) zur graphischen Darstellung von Daten,
[IPython](http://ipython.org/), eine interaktive Python-Konsole, die für das
[Projekt Jupyter](https://jupyter.org/), das unter anderem die Jupyter
Notebooks zur Verfügung stellt, von zentraler Bedeutung war und ist,
[SymPy](http://sympy.org/) für das symbolische Rechnen sowie das im
{numref}`readfile` bereits erwähnte [pandas](http://pandas.pydata.org/),
das fortgeschrittene Datenstrukturen und vielfältige Methoden zu einer
effizienten Datenanalyse bereithält.

Auf der Basis dieser Pakete haben einzelne wissenschaftliche Disziplinen
umfangreiche, auf ihre speziellen Bedürfnisse zugeschnittene Programmpakete
entwickelt. So kann [Astropy](https://www.astropy.org/) als Standard in der
Astronomie angesehen werden. [QuTiP](http://qutip.org/), die *Quantum Toolbox
in Python* erlaubt die Simulation von Quantensystemen. Für Problemstellungen,
die sich mit finite-Elemente-Methoden lösen lassen, steht
[FEniCS](https://fenicsproject.org/) zur Verfügung. Diese Aufzählung könnte
fast beliebig fortgesetzt werden und soll nur dazu dienen, einen allerersten
Eindruck von der Vielfalt der zur Verfügung stehenden
Python-Programmbibliotheken zu geben.

````{margin}
```{seealso} 
Quellen für hier besprochene Programmpakete:
[NumPy auf Github](https://github.com/numpy/numpy),
[SciPy auf Github](https://github.com/scipy/scipy)
```
````

Nachdem die Benutzung professioneller Programmpakete gelegentlich mit hohen
Kosten verbunden sein kann, ist es erwähnenswert, dass die hier aufgeführten
Pakete frei verfügbar, aber dennoch von sehr hoher Qualität sind. Zwei Beispiele
prominenter Forschungsprojekte, deren Arbeit wesentlich auf einigen der hier
genannten Pakete, sind in {numref}`warumpython` genannt. Darüber hinaus ist
der Quellcode der Pakete verfügbar, so dass man sich bei Bedarf auch die
konkrete Implementierung ansehen sowie zur Weiterentwicklung beitragen kann.

## Installation

Da NumPy und SciPy nicht in der Python-Standardbibliothek enthalten sind, stehen
diese Programmpakete auch bei einer vorhandenen Python-Installation nicht
automatisch zur Verfügung. Dies lässt sich leicht überprüfen, indem man versucht,
die beiden Pakete zu importieren. Schlägt dies fehl, so erhält man einen
`ImportError`, der impliziert, dass Python die Pakete nicht finden kann.
Außerdem lässt sich die installierte Version anzeigen, was deswegen interessant
sein kann, weil gelegentlich neue Funktionalität zu den Paketen hinzugefügt
wird. Beachten Sie, dass vor und nach `version` jeweils zwei Unterstriche
stehen müssen.

In [1]:
import numpy
import scipy

print(f'{numpy.__version__ = }')
print(f'{scipy.__version__ = }')

numpy.__version__ = '1.19.2'
scipy.__version__ = '1.5.2'


Eine einfache und empfehlenswerte Möglichkeit, NumPy und SciPy unter Windows,
MacOS oder Linuxvarianten wie Ubuntu verfügbar zu machen, besteht darin, die
[Anaconda-Distribution](https://www.anaconda.com/products/individual) zu
installieren. Dabei werden allerdings gleichzeitig zahlreiche andere, für
wissenschaftliche Zwecke interessante Programmpakete installiert.  Ist dies
nicht erwünscht, zum Beispiel wegen des relativ großen Bedarfs an
Speicherplatz, kann man NumPy und SciPy auch gezielt auf einem der Wege
installieren, die in der [Installationsanleitung für
NumPy](https://numpy.org/install/) und der [Installationsanleitung für
SciPy](https://www.scipy.org/install.html) beschrieben sind.

## Arrays und Anwendungen

Für die Arbeit mit dem NumPy-Paket ist es üblich, für `numpy` die Abkürzung
`np` einzuführen.

In [2]:
import numpy as np

Dies bedeutet, dass man bei der Verwendung von NumPy vor die entsprechenden
Funktionen jeweils `np.` setzen muss. Diese Abkürzung verringert den Tippaufwand
und macht zum anderen sofort erkenntlich, wenn es sich um eine Funktion aus dem
NumPy-Paket handelt. Dies ist unter anderem deswegen wichtig, weil NumPy unter
anderem auch Funktionen wie die Exponentialfunktion {func}`exp` zur Verfügung
stellt, die von der Exponentialfunktion aus dem `math`-Modul unterschieden werden
muss.

Das zentrale Objekt, das durch das NumPy-Paket zur Verfügung gestellt wird, ist
das `ndarray`, wobei die Abkürzung für N-dimensionales Array steht. Hiermit lassen
sich also Vektoren und Matrizen von im Prinzip beliebiger Dimension darstellen,
wobei alle Einträge vom gleichen Datentyp sind.

Es gibt eine ganze Reihe von Möglichkeiten, solche Arrays zu konstruieren. Wir
beginnen damit eine Matrix aus einer Liste oder im Allgemeinen Listen von Listen
zu erzeugen.

In [3]:
matrixA = np.array([[1.3, 2.5], [-1.7, 3.9]])
print(type(matrixA))
print(matrixA)

<class 'numpy.ndarray'>
[[ 1.3  2.5]
 [-1.7  3.9]]


Für `ndarray`s ist eine Matrixmultiplikation definiert. Um dies zu demonstrieren,
definieren wir ein zweites Array und führen die Matrixmultiplikation aus. Dafür
können wir die Funktion `np.dot` verwenden oder den `@`-Operator, der in moderneren
Versionen des NumPy-Pakets definiert ist. Anschließend überprüfen wir das Ergebnis
am 00-Element.

In [4]:
matrixB = np.array([[2.1, -4.5], [0.9, -2.1]])
print(matrixA)
print()
print(matrixB)
print()
print(matrixA @ matrixB)
print()
print(f'{matrixA[0, 0]}*{matrixB[0, 0]} + {matrixA[0, 1]}*{matrixB[1, 0]} = '
      f'{matrixA[0, 0]*matrixB[0, 0] + matrixA[0, 1]*matrixB[1, 0]}')

[[ 1.3  2.5]
 [-1.7  3.9]]

[[ 2.1 -4.5]
 [ 0.9 -2.1]]

[[  4.98 -11.1 ]
 [ -0.06  -0.54]]

1.3*2.1 + 2.5*0.9 = 4.98


Dabei zeigen die letzten beiden Zeilen, wie man Elemente des Arrays adressieren
kann, nämlich indem die Indizes für die einzelnen Dimensionen durch Komma getrennt
in eckigen Klammern angegeben werden.

```{admonition} Multiplikationsoperatoren @ und *
:class: warning
Beachten Sie, dass der normale Multiplikationsoperator `*` die beiden Matrizen
elementweise multipliziert und somit keine Matrixmultiplikation ausführt, wie
es `@` verlangt. Probieren Sie es an einem Beispiel selbst aus!
```

Wie bei Listen kann die Adressierung auch mit Hilfe von Slices erfolgen, so dass
man bequem Untermatrizen extrahieren kann. Wichtig dabei ist, dass hier kein neues
Array erzeugt wird, sondern nur eine andere Sicht auf das bereits existierende Array
bereitgestellt wird. Dadurch ist ein solcher Zugriff sehr effizient. In diesem
Beispiel verwenden wird zur schnellen Erzeugung eines etwas größeren Arrays die
{func}`arange`-Funktion, die mit mit {func}`range` vergleichbar ist, aber eben ein
zunächst eindimensionales Array erzeugt. Dieses können wir dann mit der
{func}`reshape`-Methode beispielsweise in ein zweidimensionales Array umwandeln.

In [5]:
matrixC = np.arange(36).reshape(6, 6)
print(matrixC)
print()
print(matrixC[1:3, 3:5])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

[[ 9 10]
 [15 16]]


In der letzten Zeile extrahieren wir eine Untermatrix. Dabei bezieht sich das erste
Slice auf die Zeilen und das zweite Slice auf die Spalten. So können wir auch eine
Zerlegung in Blockmatrizen vornehmen.

In [6]:
print(matrixC[:3, :3])
print()
print(matrixC[:3, 3:])
print()
print(matrixC[3:, :3])
print()
print(matrixC[3:, 3:])

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]

[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]]

[[18 19 20]
 [24 25 26]
 [30 31 32]]

[[21 22 23]
 [27 28 29]
 [33 34 35]]


Zudem kann die Möglichkeit eines Slices, die Schrittweite anzugeben, verwenden.

In [7]:
print(matrixC[::2, ::3])

[[ 0  3]
 [12 15]
 [24 27]]


Während wir bei Listen gewohnt sind, diese mit der {func}`append`-Methode um weitere
Elemente zu erweitern, sollte man ein solches Vorgehen bei Arrays vermeiden. Da dabei
jeweils ein neues Array erzeugt wird, wäre ein solches Vorgehen äußerst ineffizient.
Stattdessen legt man das Array zunächst in der benötigten Größe an, zum Beispiel mit
Hilfe von {func}`np.zeros` oder {func}`np.ones`. Das folgende Beispiel illustriert,
wie man die Dimension des Arrays sowie den Datentyp festlegen kann und was die
Multiplikation des Arrays mit einer Zahl bedeutet.

In [8]:
5*np.ones(shape=(2, 3, 4), dtype=np.int)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

```{admonition} Integer-Arrays
:class: warning
Bei Python sind wir gewohnt, dass Integer im Prinzip beliebig groß werden können.
Bei `ndarray`s mit Datentyp Integer ist dies nicht der Fall. Der mögliche
Zahlenbereich ist je nach dem gewählten Integertyp eingeschränkt. Genaueres hierzu
findet man in der [NumPy-Dokumentation zu Datentypen](https://numpy.org/doc/stable/user/basics.types.html).
```

Statt NumPy-Arrays im Detail zu diskutieren, wollen wir im Folgenden einen Eindruck von
einigen Möglichkeiten geben, die dieser Datentyp bietet. Für die Arbeit mit `ndarray`s
sollten man sich aber auf jeden Fall genauer mit diesen vertraut machen. Wir verweisen
hierzu zum Beispiel auf die [NumPy-Dokumentation](https://numpy.org/doc/stable/), aber auch
auf [Teil 1](https://youtu.be/R2rCYf3pv-M) und [Teil 2](https://youtu.be/sunNXIxIGV8) eines
Videotutorials.

Zu Beginn des Kapitels hatten wir gesehen, wie man Matrizen miteinander multiplizieren kann.
Für Vektoren erhält man auf diese Weise unmittelbar das Skalarprodukt. Darüber hinaus kann man
auch das Kreuzprodukt und das dyadische Produkt mit Hilfe von NumPy berechnen.

In [9]:
vecA = np.array([2, -3, 0])
vecB = np.array([5, 4, 0])
print(np.dot(vecA, vecB))
print()
print(np.cross(vecA, vecB))
print()
print(np.outer(vecA, vecB))

-2

[ 0  0 23]

[[ 10   8   0]
 [-15 -12   0]
 [  0   0   0]]


Statt {func}`np.dot` hätten wir natürlich auch wieder den `@`-Operator verwenden können.

Interessant sind die von NumPy zur Verfügung gestellten *universal functions* oder *ufuncs*,
die als Argumente NumPy-Arrays akzeptieren und damit effizient Funktionen in einem Schritt
für eine größere Anzahl von Argumenten auswerten können. In dem folgenden Beispiel demonstrieren
wir zugleich die Verwendung der {func}`linspace`-Funktion, um eine Liste äquidistanter Werte
zu erzeugen.

In [10]:
x = np.linspace(0, 2, 11)
print(x)
y = np.exp(x)
print(y)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]
[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183
 3.32011692 4.05519997 4.95303242 6.04964746 7.3890561 ]


Die Exponentialfunktion aus dem `math`-Modul ist dagegen nicht in der Lage, NumPy-Arrays als
Argument zu akzeptieren.

In [11]:
import math
y = math.exp(x)

TypeError: only size-1 arrays can be converted to Python scalars

An dieser Stelle wird deutlich, wie nützlich es sein kann, aus dem Code direkt ersehen zu
können, aus welchem Modul die Exponentialfunktion verwendet wird. Das NumPy-Paket stellt
*ufuncs* für die üblichen Standardfunktionen zur Verfügung. Für viele spezielle Funktionen
wird man im SciPy-Paket fündig.

Zum Abschluss dieses kurzen Einblicks in das NumPy-Paket wollen wir noch einen Blick auf
häufig benötigte Funktionen aus der linearen Algebra werfen. Diese befinden sich im `linalg`-Modul
von NumPy, das üblicherweise unter dem Namen `LA` importiert wird.

In [12]:
from numpy import linalg as LA

Für die Beispiele verwenden wir der Übersichtlichkeit halber nur 2×2-Matrizen, für die wir
alle Rechnungen natürlich auch leicht analytisch durchführen könnten. Selbstverständlich kann
NumPy auch mit viel größeren Matrizen umgehen. Wir definieren also eine 2×2-Matrix und berechnen
zunächst ihre Determinante.

In [13]:
a = np.array([[1, 3], [2, 5]])
print(LA.det(a))

-1.0


Als nächstes berechnen wir die Inverse und obwohl bei diesem Wert der Determinante die Korrektheit
des Ergebnisses mehr oder weniger offensichtlich ist, berechnen wir gleich noch das Produkt
aus der Matrix und ihrer Inversen, das erwartungsgemäß die Einheitsmatrix ergibt.

In [14]:
a_inv = LA.inv(a)
print(a_inv)
print(a @ a_inv)

[[-5.  3.]
 [ 2. -1.]]
[[1. 0.]
 [0. 1.]]


Für Anwendungen sehr wichtig ist die Möglichkeit, Eigenwertprobleme zu lösen. Berechnen wir also
die Eigenwerte und Eigenvektoren der Matrix.

In [15]:
eigenwerte, eigenvektoren = LA.eig(a)
print(eigenwerte)
print(eigenwerte[0]*eigenwerte[1])
print(eigenvektoren)

[-0.16227766  6.16227766]
-0.9999999999999984
[[-0.93246475 -0.50245469]
 [ 0.36126098 -0.86460354]]


der zweiten Ausgabezeile entnehmen als ersten Test, dass das Produkt der Eigenwerte, bis auf
Rundungsfehler, gleich der oben erhaltenen Determinanten ist. Überprüfen wir zum Abschluss noch
die Korrektheit der Eigenvektoren.

In [16]:
for idx in range(2):
    print(a @ eigenvektoren[:, idx],
          eigenwerte[idx] * eigenvektoren[:, idx])

[ 0.1513182  -0.05862459] [ 0.1513182  -0.05862459]
[-3.09626531 -5.32792709] [-3.09626531 -5.32792709]


Da der erste Index des Array `eigenvektoren` der Zeilenindex ist, während der zweite Index der
Spaltenindex ist, sehen wir, dass die Eigenvektoren in diesem Array in den Spalten stehen.

## Numerische Integration

## Integration gewöhnlicher Differentialgleichungen